repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --config, ./ruff.toml ]
      # Run the formatter.
      - id: ruff-format
        args: [ --config, ./ruff.toml ]

