# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x01\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x17\n\x06gender\x18\x03 \x01(\x0e\x32\x07.Gender\x12#\n\x03map\x18\x04 \x03(\x0b\x32\x16.HelloRequest.MapEntry\x12+\n\x07\x61\x64\x64Time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t*\x1e\n\x06Gender\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x02\x32\x33\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x42\x31Z/github.com/xiangnan0811/goTest/grpc_hello/hellob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/xiangnan0811/goTest/grpc_hello/hello'
  _HELLOREQUEST_MAPENTRY._options = None
  _HELLOREQUEST_MAPENTRY._serialized_options = b'8\001'
  _globals['_GENDER']._serialized_start=274
  _globals['_GENDER']._serialized_end=304
  _globals['_HELLOREQUEST']._serialized_start=49
  _globals['_HELLOREQUEST']._serialized_end=241
  _globals['_HELLOREQUEST_MAPENTRY']._serialized_start=199
  _globals['_HELLOREQUEST_MAPENTRY']._serialized_end=241
  _globals['_HELLOREPLY']._serialized_start=243
  _globals['_HELLOREPLY']._serialized_end=272
  _globals['_GREETER']._serialized_start=306
  _globals['_GREETER']._serialized_end=357
# @@protoc_insertion_point(module_scope)
